// ==UserScript==
// @name コネコネ（仮）
// @description ニコニコ（Re:仮）の補助ツール。
// @version 0.3.0
// @homepage https://github.com/sevenc-nanashi/conecone-kakkokari
// @match https://www.nicovideo.jp/*
// @updateURL https://raw.githubusercontent.com/sevenc-nanashi/conecone-kakkokari/built/index.user.js
// @downloadURL https://raw.githubusercontent.com/sevenc-nanashi/conecone-kakkokari/built/index.user.js
// @sandbox MAIN_WORLD
// ==/UserScript==

"use strict";(()=>{var a=Object.getPrototypeOf,f,b,c,_,T={isConnected:1},W=1e3,g,E={},B=a(T),x=a(a),d,M=(e,t,l,r)=>(e??(setTimeout(l,r),new Set)).add(t),A=(e,t,l)=>{let r=c;c=t;try{return e(l)}catch(n){return console.error(n),l}finally{c=r}},u=e=>e.filter(t=>t._dom?.isConnected),j=e=>g=M(g,e,()=>{for(let t of g)t._bindings=u(t._bindings),t._listeners=u(t._listeners);g=d},W),w={get val(){return c?._getters?.add(this),this.rawVal},get oldVal(){return c?._getters?.add(this),this._oldVal},set val(e){c?._setters?.add(this),e!==this.rawVal&&(this.rawVal=e,this._bindings.length+this._listeners.length?(b?.add(this),f=M(f,this,F)):this._oldVal=e)}},L=e=>({__proto__:w,rawVal:e,_oldVal:e,_bindings:[],_listeners:[]}),m=(e,t)=>{let l={_getters:new Set,_setters:new Set},r={f:e},n=_;_=[];let o=A(e,l,t);o=(o??document).nodeType?o:new Text(o);for(let s of l._getters)l._setters.has(s)||(j(s),s._bindings.push(r));for(let s of _)s._dom=o;return _=n,r._dom=o},S=(e,t=L(),l)=>{let r={_getters:new Set,_setters:new Set},n={f:e,s:t};n._dom=l??_?.push(n)??T,t.val=A(e,r,t.rawVal);for(let o of r._getters)r._setters.has(o)||(j(o),o._listeners.push(n));return t},I=(e,...t)=>{for(let l of t.flat(1/0)){let r=a(l??0),n=r===w?m(()=>l.val):r===x?m(l):l;n!=d&&e.append(n)}return e},q=(e,t,...l)=>{let[r,...n]=a(l[0]??0)===B?l:[{},...l],o=e?document.createElementNS(e,t):document.createElement(t);for(let[s,i]of Object.entries(r)){let V=h=>h?Object.getOwnPropertyDescriptor(h,s)??V(a(h)):d,k=t+","+s,C=E[k]??(E[k]=V(a(o))?.set??0),D=s.startsWith("on")?(h,N)=>{let O=s.slice(2);o.removeEventListener(O,N),o.addEventListener(O,h)}:C?C.bind(o):o.setAttribute.bind(o,s),v=a(i??0);s.startsWith("on")||v===x&&(i=S(i),v=w),v===w?m(()=>(D(i.val,i._oldVal),o)):D(i)}return I(o,...n)},P=e=>({get:(t,l)=>q.bind(d,e,l)}),z=new Proxy(e=>new Proxy(q,P(e)),P()),G=(e,t)=>t?t!==e&&e.replaceWith(t):e.remove(),F=()=>{let e=0,t=[...f].filter(r=>r.rawVal!==r._oldVal);do{b=new Set;for(let r of new Set(t.flatMap(n=>n._listeners=u(n._listeners))))S(r.f,r.s,r._dom),r._dom=d}while(++e<100&&(t=[...b]).length);let l=[...f].filter(r=>r.rawVal!==r._oldVal);f=d;for(let r of new Set(l.flatMap(n=>n._bindings=u(n._bindings))))G(r._dom,m(r.f,r._dom)),r._dom=d;for(let r of l)r._oldVal=r.rawVal},K=(e,t)=>G(e,m(t,e)),y={add:I,tags:z,state:L,derive:S,hydrate:K};var{a:R,div:p,path:U,span:Z}=y.tags,{svg:$}=y.tags("http://www.w3.org/2000/svg"),H=()=>{if(localStorage.getItem("conecone-rikari-read"))return;let e=document.querySelector(".nico-CommonHeaderRoot");if(!e){setTimeout(H,100);return}let t=$({viewBox:"0 0 24 24",fill:"none",class:"common-header-3drezb"});t.innerHTML=`
  <path fill-rule="evenodd" clip-rule="evenodd"
        d="M17.357 12a.498.498 0 01-.146.356l-8.29 8.29a.5.5 0 01-.708 0l-1.41-1.41a.5.5 0 010-.707L13.333 12l-6.53-6.53a.5.5 0
        010-.707l1.41-1.41a.5.5 0 01.707 0l8.29 8.29a.499.499 0 01.147.357Z"
        style="fill: rgb(24, 180, 230) !important;"></path>`.replace(/\s+(\s)/g,"$1"),e.insertBefore(p({class:"common-header-fqlnpx"},p({class:"common-header-1fxu773",style:"background-color: #18b4e6;"},R({target:"_blank",href:"https://github.com/sevenc-nanashi/conecone-kakkokari/blob/main/MESSAGE.md",class:"common-header-1524g3q",onclick:()=>localStorage.setItem("conecone-rikari-read","true")},p({class:"common-header-11rms0d"},p({class:"common-header-1gedanw"},p({class:"common-header-1udne4d"},"\u30B3\u30CD\u30B3\u30CD\uFF08\u4EEE\uFF09\u306B\u3064\u3044\u3066"),Z({class:"common-header-sgyyjv"},t)))))),e.firstChild)};H();})();
